global:
  resolve_timeout: 10s

route:
  group_by: ['alertname']
  group_wait: 3s
  receiver: 'email'
  routes:
  - receiver: 'telegram_bot'
    group_wait: 10s
    matchers:
    - severity="critical"
  - receiver: 'email'
    group_wait: 10s
    matchers:
    - severity="warning"

receivers:
- name: 'telegram_bot'
  telegram_configs:
  - bot_token: '<BOT_TOKEN>'
    api_url: 'https://api.telegram.org'
    chat_id: <CHAT_ID>
    parse_mode: 'HTML'
- name: 'email'
  email_configs:
  - to: thomasxiii@gmail.com
    from: thomasxiii@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: thomasxiii@gmail.com
    auth_identity: thomasxiii@gmail.com
    auth_password: <PASSWORD> 
    send_resolved: true
