global:
  scrape_interval: 10s
  external_labels:
    site: prod

scrape_configs:
  - job_name: prometheus_master
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node_exporter
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: mysql_exporter
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9104']
  - job_name: balckbox_exporter
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9115']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://wordpress.local    # Target to probe with http.
        - http://google.com
        - http://fake.url
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

remote_write:
  - url: http://localhost:9009/api/v1/push
